name: "Updates 5.JSON"

on: []

jobs:
  updatetoday:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pull changes
        run: git pull --force
      - name: Update 5
        run: curl -sb -H "Accept':' application/json" https://gymbot.netlify.app/print > 5.json
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GymbotUpdate-Bot"
          git add 5.json
          git commit -m "`date +'%d/%m/%Y'` 5.json updated"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
